var projectThumb = [
  { id: 1, filename: "project1", name: "Concreting" },
  { id: 2, filename: "project2", name: "Renovation" },
  { id: 3, filename: "project3", name: "Renovation" },
  { id: 4, filename: "project4", name: "Renovation" },
  { id: 5, filename: "project5", name: "Renovation" },
  { id: 6, filename: "project6", name: "Renovation" },
  { id: 7, filename: "project7", name: "Renovation" },
  { id: 8, filename: "project8", name: "Concreting" },
  { id: 9, filename: "project9", name: "Renovation" },
  { id: 10, filename: "project10", name: "Concreting" },
  { id: 11, filename: "project11", name: "Renovation" },
  { id: 12, filename: "project12", name: "Construction" },
  { id: 13, filename: "project13", name: "Renovation" },
  { id: 14, filename: "project14", name: "Construction" },
  { id: 15, filename: "project15", name: "Renovation" },
  { id: 16, filename: "project16", name: "Construction" },
  { id: 17, filename: "project17", name: "Renovation" },
  { id: 18, filename: "project18" },
  { id: 19, filename: "project19" },
  { id: 20, filename: "project20" },
  { id: 21, filename: "project21" },
  { id: 22, filename: "project22" },
  { id: 23, filename: "project23" },
  { id: 24, filename: "project24" },
  { id: 25, filename: "project25" },
  { id: 26, filename: "project26" },
  { id: 27, filename: "project27" },
  { id: 28, filename: "project28" },
  { id: 29, filename: "project29" },
  { id: 30, filename: "project30" },
  { id: 31, filename: "project31" },
  { id: 32, filename: "project32" },
  { id: 33, filename: "project33" },
  { id: 34, filename: "project34" },
  { id: 35, filename: "project35" },
  { id: 36, filename: "project36" },
  { id: 37, filename: "project37" },
  { id: 38, filename: "project38" },
  { id: 39, filename: "project39" },
  { id: 40, filename: "project40" },
]